# Generated by Django 3.2.5 on 2023-01-16 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'First Name must contain only alphabetical characters')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Last Name must contain only alphabetical characters')]),
        ),
    ]
