# Generated by Django 3.2.5 on 2022-12-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='academic_Year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.academicyear'),
        ),
    ]
