# Generated by Django 3.2.5 on 2023-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='miscellaneous',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
