# Generated by Django 3.2.5 on 2023-01-13 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
