# Generated by Django 3.2.5 on 2023-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='miscellaneous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
