# Generated by Django 3.2.5 on 2023-01-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_miscellaneous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='miscellaneous',
        ),
    ]
