# Generated by Django 3.2.5 on 2022-12-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_Year', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['academic_Year'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('GRADE 7', 'GRADE 7'), ('GRADE 8', 'GRADE 8'), ('GRADE 9', 'GRADE 9'), ('GRADE 10', 'GRADE 10'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR')], default='GRADE 7', max_length=15, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1ST QUARTER', '1ST QUARTER'), ('2ND QUARTER', '2ND QUARTER'), ('3RD QUARTER', '3RD QUARTER'), ('4TH QUARTER', '4TH QUARTER')], default='1ST QUARTER', max_length=15, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['quarter'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=15)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.level')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('level', 'section')},
            },
        ),
    ]
