# Generated by Django 3.2.5 on 2023-01-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='suffix_Name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
