# Generated by Django 3.2.5 on 2023-01-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_students_overall_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='overall_average',
        ),
    ]
