# Generated by Django 3.2.5 on 2023-01-16 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_students_overall_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='LRN',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'LRN must be a 12 digit number')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_Name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'First Name must contain only alphabetical characters')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_Name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Last Name must contain only alphabetical characters')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_Name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Middle Name must contain only alphabetical characters')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='suffix_Name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Suffix Name must contain only alphabetical characters')]),
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('first_Name', 'last_Name')},
        ),
    ]
